// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/forex.proto

package visa

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Address card address
type Address struct {
	// @inject_tag: json:"city,omitempty"
	City string `protobuf:"bytes,1,opt,name=City,proto3" json:"city,omitempty"`
	// @inject_tag: json:"country,omitempty"
	Country string `protobuf:"bytes,2,opt,name=Country,proto3" json:"country,omitempty"`
	// @inject_tag: json:"county,omitempty"
	County string `protobuf:"bytes,3,opt,name=County,proto3" json:"county,omitempty"`
	// @inject_tag: json:"state,omitempty"
	State string `protobuf:"bytes,4,opt,name=State,proto3" json:"state,omitempty"`
	// @inject_tag: json:"zipCode,omitempty"
	ZipCode              string   `protobuf:"bytes,5,opt,name=ZipCode,proto3" json:"zipCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_beee972f8fd3a43c, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

// CardAcceptor id
type CardAcceptor struct {
	// @inject_tag: json:"adress,omitempty"
	Address *Address `protobuf:"bytes,1,opt,name=Address,proto3" json:"adress,omitempty"`
	// @inject_tag: json:"idcode,omitempty"
	IDCode string `protobuf:"bytes,2,opt,name=IDCode,proto3" json:"idcode,omitempty"`
	// @inject_tag: json:"name,omitempty"
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"name,omitempty"`
	// @inject_tag: json:"terminalId,omitempty"
	TerminalID           string   `protobuf:"bytes,4,opt,name=TerminalID,proto3" json:"terminalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardAcceptor) Reset()         { *m = CardAcceptor{} }
func (m *CardAcceptor) String() string { return proto.CompactTextString(m) }
func (*CardAcceptor) ProtoMessage()    {}
func (*CardAcceptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_beee972f8fd3a43c, []int{1}
}

func (m *CardAcceptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardAcceptor.Unmarshal(m, b)
}
func (m *CardAcceptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardAcceptor.Marshal(b, m, deterministic)
}
func (m *CardAcceptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardAcceptor.Merge(m, src)
}
func (m *CardAcceptor) XXX_Size() int {
	return xxx_messageInfo_CardAcceptor.Size(m)
}
func (m *CardAcceptor) XXX_DiscardUnknown() {
	xxx_messageInfo_CardAcceptor.DiscardUnknown(m)
}

var xxx_messageInfo_CardAcceptor proto.InternalMessageInfo

func (m *CardAcceptor) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *CardAcceptor) GetIDCode() string {
	if m != nil {
		return m.IDCode
	}
	return ""
}

func (m *CardAcceptor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CardAcceptor) GetTerminalID() string {
	if m != nil {
		return m.TerminalID
	}
	return ""
}

type VisaForexRequest struct {
	// @inject_tag: json:"cardAcceptor"
	CardAcceptor *CardAcceptor `protobuf:"bytes,1,opt,name=CardAcceptor,proto3" json:"cardAcceptor"`
	// @inject_tag: json:"destinationCurrencyCode,omitempty"
	DestinationCurrencyCode string `protobuf:"bytes,2,opt,name=DestinationCurrencyCode,proto3" json:"destinationCurrencyCode,omitempty"`
	// @inject_tag: json:"markUpRate,omitempty"
	MarkUpRate string `protobuf:"bytes,3,opt,name=MarkUpRate,proto3" json:"markUpRate,omitempty"`
	// @inject_tag: json:"retrievalReferenceNumber,omitempty"
	RetrievalReferenceNumber string `protobuf:"bytes,4,opt,name=RetrievalReferenceNumber,proto3" json:"retrievalReferenceNumber,omitempty"`
	// @inject_tag: json:"sourceAmount,omitempty"
	SourceAmount string `protobuf:"bytes,5,opt,name=SourceAmount,proto3" json:"sourceAmount,omitempty"`
	// @inject_tag: json:"sourceCurrencyCode,omitempty"
	SourceCurrencyCode string `protobuf:"bytes,6,opt,name=SourceCurrencyCode,proto3" json:"sourceCurrencyCode,omitempty"`
	// @inject_tag: json:"systemsTraceAuditNumber,omitempty"
	SystemsTraceAuditNumber string   `protobuf:"bytes,7,opt,name=SystemsTraceAuditNumber,proto3" json:"systemsTraceAuditNumber,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *VisaForexRequest) Reset()         { *m = VisaForexRequest{} }
func (m *VisaForexRequest) String() string { return proto.CompactTextString(m) }
func (*VisaForexRequest) ProtoMessage()    {}
func (*VisaForexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_beee972f8fd3a43c, []int{2}
}

func (m *VisaForexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisaForexRequest.Unmarshal(m, b)
}
func (m *VisaForexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisaForexRequest.Marshal(b, m, deterministic)
}
func (m *VisaForexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisaForexRequest.Merge(m, src)
}
func (m *VisaForexRequest) XXX_Size() int {
	return xxx_messageInfo_VisaForexRequest.Size(m)
}
func (m *VisaForexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VisaForexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VisaForexRequest proto.InternalMessageInfo

func (m *VisaForexRequest) GetCardAcceptor() *CardAcceptor {
	if m != nil {
		return m.CardAcceptor
	}
	return nil
}

func (m *VisaForexRequest) GetDestinationCurrencyCode() string {
	if m != nil {
		return m.DestinationCurrencyCode
	}
	return ""
}

func (m *VisaForexRequest) GetMarkUpRate() string {
	if m != nil {
		return m.MarkUpRate
	}
	return ""
}

func (m *VisaForexRequest) GetRetrievalReferenceNumber() string {
	if m != nil {
		return m.RetrievalReferenceNumber
	}
	return ""
}

func (m *VisaForexRequest) GetSourceAmount() string {
	if m != nil {
		return m.SourceAmount
	}
	return ""
}

func (m *VisaForexRequest) GetSourceCurrencyCode() string {
	if m != nil {
		return m.SourceCurrencyCode
	}
	return ""
}

func (m *VisaForexRequest) GetSystemsTraceAuditNumber() string {
	if m != nil {
		return m.SystemsTraceAuditNumber
	}
	return ""
}

type VisaForexReply struct {
	// @inject_tag: json:"conversionRate,omitempty"
	ConversionRate float32 `protobuf:"fixed32,1,opt,name=ConversionRate,proto3" json:"conversionRate,omitempty"`
	// @inject_tag: json:"destinationAmount,omitempty"
	DestinationAmount string `protobuf:"bytes,2,opt,name=DestinationAmount,proto3" json:"destinationAmount,omitempty"`
	// @inject_tag: json:"markUpRateApplied,omitempty"
	MarkUpRateApplied string `protobuf:"bytes,3,opt,name=MarkUpRateApplied,proto3" json:"markUpRateApplied,omitempty"`
	// @inject_tag: json:"originalDestnAmtBeforeMarkUp,omitempty"
	OriginalDestnAmtBeforeMarkUp string   `protobuf:"bytes,4,opt,name=OriginalDestnAmtBeforeMarkUp,proto3" json:"originalDestnAmtBeforeMarkUp,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *VisaForexReply) Reset()         { *m = VisaForexReply{} }
func (m *VisaForexReply) String() string { return proto.CompactTextString(m) }
func (*VisaForexReply) ProtoMessage()    {}
func (*VisaForexReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_beee972f8fd3a43c, []int{3}
}

func (m *VisaForexReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisaForexReply.Unmarshal(m, b)
}
func (m *VisaForexReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisaForexReply.Marshal(b, m, deterministic)
}
func (m *VisaForexReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisaForexReply.Merge(m, src)
}
func (m *VisaForexReply) XXX_Size() int {
	return xxx_messageInfo_VisaForexReply.Size(m)
}
func (m *VisaForexReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VisaForexReply.DiscardUnknown(m)
}

var xxx_messageInfo_VisaForexReply proto.InternalMessageInfo

func (m *VisaForexReply) GetConversionRate() float32 {
	if m != nil {
		return m.ConversionRate
	}
	return 0
}

func (m *VisaForexReply) GetDestinationAmount() string {
	if m != nil {
		return m.DestinationAmount
	}
	return ""
}

func (m *VisaForexReply) GetMarkUpRateApplied() string {
	if m != nil {
		return m.MarkUpRateApplied
	}
	return ""
}

func (m *VisaForexReply) GetOriginalDestnAmtBeforeMarkUp() string {
	if m != nil {
		return m.OriginalDestnAmtBeforeMarkUp
	}
	return ""
}

func init() {
	proto.RegisterType((*Address)(nil), "visa.Address")
	proto.RegisterType((*CardAcceptor)(nil), "visa.CardAcceptor")
	proto.RegisterType((*VisaForexRequest)(nil), "visa.VisaForexRequest")
	proto.RegisterType((*VisaForexReply)(nil), "visa.VisaForexReply")
}

func init() { proto.RegisterFile("pb/forex.proto", fileDescriptor_beee972f8fd3a43c) }

var fileDescriptor_beee972f8fd3a43c = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x8b, 0xd3, 0x50,
	0x10, 0xb5, 0xb5, 0xdb, 0xe2, 0xb8, 0x16, 0x1d, 0x96, 0x1a, 0x44, 0x44, 0xf2, 0xa0, 0x3e, 0x48,
	0x85, 0x15, 0x44, 0x7c, 0xcb, 0xa6, 0x28, 0xfb, 0xe0, 0x0a, 0xe9, 0x2a, 0xe2, 0xdb, 0x6d, 0x32,
	0x2b, 0x17, 0x93, 0xdc, 0x38, 0xf7, 0xa6, 0x98, 0x27, 0x1f, 0xfc, 0x93, 0xfe, 0x0a, 0x7f, 0x83,
	0xdc, 0x0f, 0x77, 0xd3, 0xd6, 0xee, 0xdb, 0xcc, 0x39, 0x93, 0xe1, 0x9c, 0x93, 0xb9, 0x30, 0x6d,
	0x56, 0x2f, 0x2e, 0x14, 0xd3, 0x8f, 0x79, 0xc3, 0xca, 0x28, 0x1c, 0xad, 0xa5, 0x16, 0xf1, 0x4f,
	0x98, 0x24, 0x45, 0xc1, 0xa4, 0x35, 0x22, 0x8c, 0x52, 0x69, 0xba, 0x68, 0xf0, 0x78, 0xf0, 0xec,
	0x56, 0xe6, 0x6a, 0x8c, 0x60, 0x92, 0xaa, 0xb6, 0x36, 0xdc, 0x45, 0x43, 0x07, 0xff, 0x6b, 0x71,
	0x06, 0x63, 0x57, 0x76, 0xd1, 0x4d, 0x47, 0x84, 0x0e, 0x8f, 0xe0, 0x60, 0x69, 0x84, 0xa1, 0x68,
	0xe4, 0x60, 0xdf, 0xd8, 0x3d, 0x5f, 0x64, 0x93, 0xaa, 0x82, 0xa2, 0x03, 0xbf, 0x27, 0xb4, 0xf1,
	0xaf, 0x01, 0x1c, 0xa6, 0x82, 0x8b, 0x24, 0xcf, 0xa9, 0x31, 0x8a, 0xf1, 0xe9, 0xa5, 0x22, 0xa7,
	0xe4, 0xf6, 0xf1, 0x9d, 0xb9, 0x55, 0x3a, 0x0f, 0x60, 0x76, 0xa9, 0x77, 0x06, 0xe3, 0xd3, 0x85,
	0x5b, 0xe9, 0xa5, 0x85, 0xce, 0xfa, 0x38, 0x13, 0x15, 0x05, 0x5d, 0xae, 0xc6, 0x47, 0x00, 0xe7,
	0xc4, 0x95, 0xac, 0x45, 0x79, 0xba, 0x08, 0xd2, 0x7a, 0x48, 0xfc, 0x67, 0x08, 0x77, 0x3f, 0x49,
	0x2d, 0xde, 0xda, 0x80, 0x32, 0xfa, 0xde, 0x92, 0x36, 0xf8, 0x6a, 0x53, 0x59, 0x90, 0x83, 0x5e,
	0x4e, 0x9f, 0xc9, 0x36, 0x1d, 0xbc, 0x86, 0xfb, 0x0b, 0xd2, 0x46, 0xd6, 0xc2, 0x48, 0x55, 0xa7,
	0x2d, 0x33, 0xd5, 0x79, 0xd7, 0x53, 0xba, 0x8f, 0xb6, 0x32, 0xdf, 0x0b, 0xfe, 0xf6, 0xb1, 0xc9,
	0x6c, 0x82, 0xde, 0x40, 0x0f, 0xc1, 0x37, 0x10, 0x65, 0x64, 0x58, 0xd2, 0x5a, 0x94, 0x19, 0x5d,
	0x90, 0xfd, 0x92, 0xce, 0xda, 0x6a, 0x45, 0x1c, 0x4c, 0xed, 0xe5, 0x31, 0x86, 0xc3, 0xa5, 0x6a,
	0x39, 0xa7, 0xa4, 0xb2, 0x7f, 0x2a, 0xfc, 0x87, 0x0d, 0x0c, 0xe7, 0x80, 0xbe, 0xdf, 0x10, 0x3d,
	0x76, 0x93, 0xff, 0x61, 0xac, 0xd3, 0x65, 0xa7, 0x0d, 0x55, 0xfa, 0x9c, 0x45, 0x4e, 0x49, 0x5b,
	0x48, 0x13, 0xe4, 0x4c, 0xbc, 0xd3, 0x3d, 0x74, 0xfc, 0x7b, 0x00, 0xd3, 0x5e, 0xe0, 0x4d, 0xd9,
	0xe1, 0x13, 0x98, 0xa6, 0xaa, 0x5e, 0x13, 0x6b, 0xa9, 0x6a, 0x17, 0x80, 0x0d, 0x7c, 0x98, 0x6d,
	0xa1, 0xf8, 0x1c, 0xee, 0xf5, 0xf2, 0x0b, 0x6e, 0x7c, 0xb0, 0xbb, 0x84, 0x9d, 0xbe, 0x0a, 0x30,
	0x69, 0x9a, 0x52, 0x52, 0x11, 0x92, 0xdd, 0x25, 0xf0, 0x04, 0x1e, 0x7e, 0x60, 0xf9, 0xd5, 0x5e,
	0x85, 0x5d, 0x55, 0x27, 0x95, 0x39, 0x21, 0xfb, 0x6a, 0xfc, 0x68, 0x08, 0xf9, 0xda, 0x99, 0xe3,
	0xcf, 0xbd, 0x53, 0x5a, 0x12, 0xaf, 0x65, 0x4e, 0xb8, 0x00, 0x7c, 0x47, 0xc6, 0x41, 0x57, 0x6e,
	0x70, 0xe6, 0x4f, 0x69, 0xfb, 0xf0, 0x1e, 0x1c, 0xed, 0xe0, 0x4d, 0xd9, 0xc5, 0x37, 0x56, 0x63,
	0xf7, 0x72, 0x5f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x18, 0xca, 0x38, 0xcb, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VisaForexServiceClient is the client API for VisaForexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VisaForexServiceClient interface {
	GetForexConversion(ctx context.Context, in *VisaForexRequest, opts ...grpc.CallOption) (*VisaForexReply, error)
}

type visaForexServiceClient struct {
	cc *grpc.ClientConn
}

func NewVisaForexServiceClient(cc *grpc.ClientConn) VisaForexServiceClient {
	return &visaForexServiceClient{cc}
}

func (c *visaForexServiceClient) GetForexConversion(ctx context.Context, in *VisaForexRequest, opts ...grpc.CallOption) (*VisaForexReply, error) {
	out := new(VisaForexReply)
	err := c.cc.Invoke(ctx, "/visa.VisaForexService/GetForexConversion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisaForexServiceServer is the server API for VisaForexService service.
type VisaForexServiceServer interface {
	GetForexConversion(context.Context, *VisaForexRequest) (*VisaForexReply, error)
}

func RegisterVisaForexServiceServer(s *grpc.Server, srv VisaForexServiceServer) {
	s.RegisterService(&_VisaForexService_serviceDesc, srv)
}

func _VisaForexService_GetForexConversion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisaForexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisaForexServiceServer).GetForexConversion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visa.VisaForexService/GetForexConversion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisaForexServiceServer).GetForexConversion(ctx, req.(*VisaForexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VisaForexService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "visa.VisaForexService",
	HandlerType: (*VisaForexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForexConversion",
			Handler:    _VisaForexService_GetForexConversion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/forex.proto",
}
