// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pb/visa.proto

package visa

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VisaService service

type VisaService interface {
	GetForexConversion(ctx context.Context, in *VisaForexRequest, opts ...client.CallOption) (*VisaForexReply, error)
}

type visaService struct {
	c    client.Client
	name string
}

func NewVisaService(name string, c client.Client) VisaService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "visa"
	}
	return &visaService{
		c:    c,
		name: name,
	}
}

func (c *visaService) GetForexConversion(ctx context.Context, in *VisaForexRequest, opts ...client.CallOption) (*VisaForexReply, error) {
	req := c.c.NewRequest(c.name, "VisaService.GetForexConversion", in)
	out := new(VisaForexReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VisaService service

type VisaServiceHandler interface {
	GetForexConversion(context.Context, *VisaForexRequest, *VisaForexReply) error
}

func RegisterVisaServiceHandler(s server.Server, hdlr VisaServiceHandler, opts ...server.HandlerOption) error {
	type visaService interface {
		GetForexConversion(ctx context.Context, in *VisaForexRequest, out *VisaForexReply) error
	}
	type VisaService struct {
		visaService
	}
	h := &visaServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&VisaService{h}, opts...))
}

type visaServiceHandler struct {
	VisaServiceHandler
}

func (h *visaServiceHandler) GetForexConversion(ctx context.Context, in *VisaForexRequest, out *VisaForexReply) error {
	return h.VisaServiceHandler.GetForexConversion(ctx, in, out)
}
